version: '3.2'

services:

  dash:
    container_name: npreview_dash
    restart: always
    build: '.'
    ports:
      - "8050:8050"
    command: gunicorn -w 1 -b :8050 app:server
    environment:
      VIRTUAL_HOST: localhost
      VIRTUAL_PORT: 8050
    volumes:
      - ./archive:/archive
      - ./assets:/assets



networks:
 default:
    external:
      name: nginx-proxy
